-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID,
       DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, 
       DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE, 
       CASE 
           WHEN DATEDIFF(DATE(END_DATE), DATE(START_DATE)) >= 29 THEN "장기 대여"
           ELSE "단기 대여"
        END as RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 and MONTH(START_DATE) = 9
ORDER BY HISTORY_ID	desc