-- 코드를 작성해주세요
SELECT I.ID, T.FISH_NAME, I.LENGTH FROM FISH_INFO I JOIN FISH_NAME_INFO T ON I.FISH_TYPE = T.FISH_TYPE WHERE I.ID IN (
    SELECT ID
    FROM FISH_INFO
    WHERE LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_TYPE = I.FISH_TYPE)
)
ORDER BY I.ID ASC;